#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to Consul running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDQ1YTIyNDRmMGNkNDY2MjQ0MGI1ZGZmZjc2ZjhkZDNiOGFjMTE0ZmY0Y2Y1MzIyMmI0M2Q4OWNmZTFlMWIxZmQ5MTg5Y2JkYmRlNDNiNzk0MGZlZjNhNjE5M2JkMDQ0ZWI2Yg==
management:
  prometheus:
    metrics:
      export:
        enabled: true
